# Generated by Django 3.2.16 on 2022-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camerastream', '0006_alter_camers_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCarLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=126)),
                ('owner', models.CharField(max_length=126)),
                ('brand', models.CharField(max_length=126)),
                ('number', models.TextField(max_length=32)),
            ],
        ),
        migrations.RenameModel(
            old_name='EntryLog',
            new_name='EntryPersonLog',
        ),
        migrations.DeleteModel(
            name='FalseEntryLog',
        ),
    ]
