# Generated by Django 3.2.16 on 2022-12-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camerastream', '0007_auto_20221217_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrycarlog',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='entrycarlog',
            name='owner',
        ),
        migrations.AddField(
            model_name='entrycarlog',
            name='date',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrycarlog',
            name='number',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='entrypersonlog',
            name='date',
            field=models.CharField(max_length=32),
        ),
    ]
