# Generated by Django 3.2.16 on 2022-12-17 21:35

import apps.data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to=apps.data.models.Person.upload_photo_to),
        ),
    ]
